services:
  - type: web
    name: medicare-hms
    env: docker
    plan: free
    rootDir: MediCare HMS
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SECURITY_USER_NAME
        value: admin
      - key: SECURITY_USER_PASSWORD
        generateValue: true
      - key: DDL_AUTO
        value: "update"
